spring.application.name=admin-service

spring.datasource.url=jdbc:postgresql://localhost:5432/fooddelivery
spring.datasource.username=postgres
spring.datasource.password=shalini

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8080